//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class acl
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string page_name { get; set; }
        public Nullable<int> page_company_id { get; set; }
        public byte allow_view { get; set; }
        public byte allow_create { get; set; }
        public byte allow_update { get; set; }
        public byte allow_delete { get; set; }
        public byte allow_print { get; set; }
    
        public virtual company company { internal get; set; }
        public virtual user user { internal get; set; }
    }
    
}
