//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class bisnis_kinerja_keuangan
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public int tahun { get; set; }
        public double laba_bersih { get; set; }
        public double modal_sendiri { get; set; }
        public double ebtit { get; set; }
        public double penyusutan { get; set; }
        public double capital_employed { get; set; }
        public double laba_operasi { get; set; }
        public double total_pendapatan_usaha { get; set; }
        public double kas { get; set; }
        public double bank { get; set; }
        public double surat_berharga { get; set; }
        public double current_liabillities { get; set; }
        public double current_asset { get; set; }
        public double total_piutang_usaha { get; set; }
        public double total_pendapatan { get; set; }
        public double total_modal_sendiri { get; set; }
        public double total_asset { get; set; }
        public double ebitda { get; set; }
        public double interest_payment { get; set; }
        public double roe { get; set; }
        public double roi { get; set; }
        public double opm { get; set; }
        public double npm { get; set; }
        public double nkk { get; set; }
        public double cash_ratio { get; set; }
        public double current_ratio { get; set; }
        public double cp { get; set; }
        public double ito { get; set; }
        public double tato { get; set; }
        public double etta { get; set; }
        public double tier { get; set; }
        public string klasifikasi { get; set; }
    
        public virtual company company { get; set; }
    }
    
}
