//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class bisnis_main
    {
        public int company_id { get; set; }
        public string profile { get; set; }
        public string struktur { get; set; }
        public string visimisi { get; set; }
        public string ad_art { get; set; }
        public string rjpp { get; set; }
        public string rkap { get; set; }
    
        public virtual company company { get; set; }
    }
    
}
