//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class bisnis_kinerja_administrasi
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public int tahun { get; set; }
        public int keuangan_bulanan { get; set; }
        public int manajemen_bulanan { get; set; }
        public int keuangan_audited { get; set; }
        public int rancangan_rkap { get; set; }
        public double nilai_keuangan_bulanan { get; set; }
        public double nilai_manajemen_bulanan { get; set; }
        public double nilai_keuangan_audited { get; set; }
        public double nilai_rancangan_rkap { get; set; }
        public double nka { get; set; }
        public string klasifikasi { get; set; }
    
        public virtual company company { get; set; }
    }
    
}
