//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class company
    {
        public company()
        {
            this.acls = new HashSet<acl>();
            this.users_jabatan = new HashSet<users_jabatan>();
        }
    
        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }
    
        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<users_jabatan> users_jabatan { get; set; }
        public virtual string nama_parent { get; set; }
    }

    public partial class company2
    {
        public company2()
        {
            this.users_jabatan = new HashSet<users_jabatan>();
        }

        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }

        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<users_jabatan> users_jabatan { get; set; }
        public virtual string nama_parent { get; set; }
    }
    
}
