//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class company
    {
        public company()
        {
            this.acls = new HashSet<acl>();
            this.bisnis_bussiness_report = new HashSet<bisnis_bussiness_report>();
            this.bisnis_kpi = new HashSet<bisnis_kpi>();
            this.bisnis_product = new HashSet<bisnis_product>();
            this.bisnis_rjpp = new HashSet<bisnis_rjpp>();
            this.bisnis_rkap = new HashSet<bisnis_rkap>();
            this.users_jabatan = new HashSet<users_jabatan>();
        }
    
        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }
    
        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<bisnis_bussiness_report> bisnis_bussiness_report { get; set; }
        public virtual ICollection<bisnis_kpi> bisnis_kpi { get; set; }
        public virtual bisnis_main bisnis_main { get; set; }
        public virtual ICollection<bisnis_product> bisnis_product { get; set; }
        public virtual ICollection<bisnis_rjpp> bisnis_rjpp { get; set; }
        public virtual ICollection<bisnis_rkap> bisnis_rkap { get; set; }
        public virtual ICollection<users_jabatan> users_jabatan { get; set; }
		public virtual string nama_parent { get; set; }
    }
    public partial class company2
    {
        public company2()
        {
            this.users_jabatan = new HashSet<users_jabatan>();
            this.bisnis_main = new HashSet<bisnis_main>();
        }

        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }

        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<users_jabatan> users_jabatan { get; set; }
        public virtual ICollection<bisnis_main> bisnis_main { internal get; set; }
        public virtual ICollection<bisnis_bussiness_report> bisnis_bussiness_report { internal get; set; }
        public virtual ICollection<bisnis_kpi> bisnis_kpi { internal get; set; }
        public virtual string nama_parent { get; set; }
    }
}
