//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class dashboard_text
    {
        public int id { get; set; }
        public string tipe { get; set; }
        public System.DateTime tgl_update { get; set; }
        public string ringkasan { get; set; }
        public string konten { get; set; }
        public int poster_user_id { get; set; }
        public string kategori { get; set; }

        public virtual user user { internal get; set; }
        public virtual user_rm_role user_rm_role { internal get; set; }
        public virtual string poster_username { get; set; }
    }
    
}
