//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class equipment_readiness_nav
    {
        public int id { get; set; }
        public int id_equipment { get; set; }
        public Nullable<double> operation { get; set; }
        public Nullable<double> boc { get; set; }
        public Nullable<double> bec { get; set; }
        public Nullable<double> monitoring { get; set; }
        public Nullable<double> performance { get; set; }
        public Nullable<double> cm_program { get; set; }
        public Nullable<double> maintenance { get; set; }
        public Nullable<double> pm_program { get; set; }
        public Nullable<double> overhaul { get; set; }
        public Nullable<double> spares { get; set; }
        public Nullable<double> lifecycle_spare { get; set; }
        public Nullable<double> main_act_spare { get; set; }
        public Nullable<double> safe_operation { get; set; }
        public Nullable<double> safeguard { get; set; }
        public Nullable<double> accesories { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<double> capacity { get; set; }
        public Nullable<double> quality { get; set; }
        public Nullable<double> sertifikasi { get; set; }
    
        public virtual equipment equipment { get; set; }
    }
    
}
