//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class kalendar_events
    {
        public int id { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string type { get; set; }
        public string priority { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<int> group_id { get; set; }
    }
    
}
