//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace relmon.Models
{
    public partial class kontak
    {
        public int id { get; set; }
        public string nama { get; set; }
        public string gedung { get; set; }
        public string alamat { get; set; }
        public string kota { get; set; }
        public string telepon { get; set; }
        public string fax { get; set; }
        public string tipe { get; set; }
    }
    
}
