//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace relmon.Models
{
    public partial class RelmonStoreEntities : DbContext
    {
        public RelmonStoreEntities()
            : base("name=RelmonStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acl> acls { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<dashboard_default> dashboard_default { get; set; }
        public DbSet<dashboard_text> dashboard_text { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<users_jabatan> users_jabatan { get; set; }
        public DbSet<users_keluarga> users_keluarga { get; set; }
        public DbSet<users_kursus> users_kursus { get; set; }
        public DbSet<users_nilai_kinerja> users_nilai_kinerja { get; set; }
        public DbSet<users_pendidikan> users_pendidikan { get; set; }
        public DbSet<users_pengalaman_kerja> users_pengalaman_kerja { get; set; }
        public DbSet<users_penghargaan> users_penghargaan { get; set; }
        public DbSet<users_penugasan> users_penugasan { get; set; }
        public DbSet<users_riwayat_gol_upah_persero> users_riwayat_gol_upah_persero { get; set; }
        public DbSet<users_sertifikasi> users_sertifikasi { get; set; }
        public DbSet<users_tindakan_disiplin> users_tindakan_disiplin { get; set; }
        public DbSet<bisnis_bussiness_report> bisnis_bussiness_report { get; set; }
        public DbSet<bisnis_kpi> bisnis_kpi { get; set; }
        public DbSet<bisnis_main> bisnis_main { get; set; }
        public DbSet<sheqms_kebijakan_HSE> sheqms_kebijakan_HSE { get; set; }
        public DbSet<sheqms_safety_talk> sheqms_safety_talk { get; set; }
        public DbSet<bisnis_rjpp> bisnis_rjpp { get; set; }
        public DbSet<bisnis_rkap> bisnis_rkap { get; set; }
        public DbSet<bisnis_product> bisnis_product { get; set; }
    }
}
