//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class system
    {
        public system()
        {
            this.equipment_groups = new HashSet<equipment_groups>();
            this.system_paf = new HashSet<system_paf>();
        }
    
        public int id { get; set; }
        public int id_unit { get; set; }
        public string nama { get; set; }
        public string kode { get; set; }
        public string funct_description { get; set; }
        public string failure_scenario { get; set; }
        public string primary_impact { get; set; }
        public string secondary_impact { get; set; }
        public string cons_econ { get; set; }
        public string cons_hs { get; set; }
        public string cons_env { get; set; }
        public string cons_total { get; set; }
        public string likelihood { get; set; }
        public string crit_code { get; set; }
        public string ram_crit { get; set; }
        public string exist_crit { get; set; }
        public string h { get; set; }
        public string e { get; set; }
        public string econ { get; set; }
        public string ram_crit_1 { get; set; }
        public string prob { get; set; }
        public string ram_crit_2 { get; set; }
        public string ram_crit_3 { get; set; }
    
        public virtual ICollection<equipment_groups> equipment_groups { get; set; }
        public virtual ICollection<system_paf> system_paf { get; set; }
        public virtual unit unit { get; set; }
    }
    
}
