//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace relmon.Models
{
    public partial class user
    {
        public user()
        {
            this.acls = new HashSet<acl>();
            this.dashboard_text = new HashSet<dashboard_text>();
            this.users_keluarga = new HashSet<users_keluarga>();
            this.users_kursus = new HashSet<users_kursus>();
            this.users_nilai_kinerja = new HashSet<users_nilai_kinerja>();
            this.users_pendidikan = new HashSet<users_pendidikan>();
            this.users_pengalaman_kerja = new HashSet<users_pengalaman_kerja>();
            this.users_penghargaan = new HashSet<users_penghargaan>();
            this.users_penugasan = new HashSet<users_penugasan>();
            this.users_riwayat_gol_upah_persero = new HashSet<users_riwayat_gol_upah_persero>();
            this.users_sertifikasi = new HashSet<users_sertifikasi>();
            this.users_tindakan_disiplin = new HashSet<users_tindakan_disiplin>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        [Display(Name = "Full Name")]
        public string fullname { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        [Display(Name = "Jabatan")]
        public Nullable<int> rm_role { get; set; }
        [Display(Name = "No Pekerja")]
        public string no_pekerja { get; set; }
        public string lokasi { get; set; }
        public string direktorat { get; set; }
        [Display(Name = "Tempat Lahir")]
        public string tempat_lahir { get; set; }
        [Display(Name = "Tgl Lahir")]
        public Nullable<System.DateTime> tgl_lahir { get; set; }
        [Display(Name = "Jenis Kelamin")]
        public Nullable<byte> jenis_kelamin { get; set; }
        public string agama { get; set; }
        [Display(Name = "Susunan Keluarga")]
        public string susunan_keluarga { get; set; }
        public string NPWP { get; set; }
        [Display(Name = "Alamat Pajak")]
        public string alamat_pajak { get; set; }
        [Display(Name = "Alamat Rumah")]
        public string alamat_rumah { get; set; }
        [Display(Name = "Alamat KTP")]
        public string alamat_ktp { get; set; }
        [Display(Name = "Tgl MPPK")]
        public Nullable<System.DateTime> tgl_mppk { get; set; }
        [Display(Name = "Tgl Pensiun")]
        public Nullable<System.DateTime> tgl_pensiun { get; set; }
        [Display(Name = "Sub Area")]
        public string sub_area { get; set; }
        [Display(Name = "Tgl Aktif")]
        public Nullable<System.DateTime> tgl_aktif { get; set; }
        [Display(Name = "TMT Dapen DPLK")]
        public Nullable<System.DateTime> tmt_dapen_dplk { get; set; }
        [Display(Name = "TMT Jabatan")]
        public Nullable<System.DateTime> tmt_jabatan { get; set; }
        [Display(Name = "TMT Gol Jabatan")]
        public Nullable<System.DateTime> tmt_gol_jabatan { get; set; }
        [Display(Name = "Gol Upah Persero")]
        public string gol_upah_persero { get; set; }
        [Display(Name = "TMT Gol Upah Persero")]
        public Nullable<System.DateTime> tmt_gol_upah_persero { get; set; }
        [Display(Name = "Gol Upah AP")]
        public string gol_upah_ap { get; set; }
        [Display(Name = "TMT Gol Upah AP")]
        public Nullable<System.DateTime> tmt_gol_upah_ap { get; set; }
        public string layering { get; set; }
        [Display(Name = "Pendidikan Terakhir")]
        public string pendidikan_terakhir { get; set; }
        [Display(Name = "Status Pekerja")]
        public string status_pekerja { get; set; }
        public string directoratecode { get; set; }
        public string directoratedesc { get; set; }
        public string departementdesc { get; set; }
        public string departementcode { get; set; }
        public string divisioncode { get; set; }
        public string divisiondesc { get; set; }
        public string functioncode { get; set; }
        public string functiondesc { get; set; }
        public string sectioncode { get; set; }
        public string sectiondesc { get; set; }
        public string groupcode { get; set; }
        public string groupdesc { get; set; }
        public string employeestatus { get; set; }
        public string phonenumber { get; set; }
    
        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<dashboard_text> dashboard_text { get; set; }
        public virtual ICollection<users_keluarga> users_keluarga { internal get; set; }
        public virtual ICollection<users_kursus> users_kursus { internal get; set; }
        public virtual ICollection<users_nilai_kinerja> users_nilai_kinerja { internal get; set; }
        public virtual ICollection<users_pendidikan> users_pendidikan { internal get; set; }
        public virtual ICollection<users_pengalaman_kerja> users_pengalaman_kerja { internal get; set; }
        public virtual ICollection<users_penghargaan> users_penghargaan { internal get; set; }
        public virtual ICollection<users_penugasan> users_penugasan { internal get; set; }
        public virtual ICollection<users_riwayat_gol_upah_persero> users_riwayat_gol_upah_persero { internal get; set; }
        public virtual ICollection<users_sertifikasi> users_sertifikasi { internal get; set; }
        public virtual ICollection<users_tindakan_disiplin> users_tindakan_disiplin { internal get; set; }
        public virtual users_jabatan users_jabatan { internal get; set; }
        public virtual users_jabatan_parent users_jabatan_parent { get; set; }
        public virtual string status_pensiun { get; set; }
    }
    
	public partial class user_rm_role
    {
        public user_rm_role()
        {
            this.users_keluarga = new HashSet<users_keluarga>();
            this.users_kursus = new HashSet<users_kursus>();
            this.users_nilai_kinerja = new HashSet<users_nilai_kinerja>();
            this.users_pendidikan = new HashSet<users_pendidikan>();
            this.users_pengalaman_kerja = new HashSet<users_pengalaman_kerja>();
            this.users_penghargaan = new HashSet<users_penghargaan>();
            this.users_penugasan = new HashSet<users_penugasan>();
            this.users_riwayat_gol_upah_persero = new HashSet<users_riwayat_gol_upah_persero>();
            this.users_sertifikasi = new HashSet<users_sertifikasi>();
            this.users_tindakan_disiplin = new HashSet<users_tindakan_disiplin>();
            this.acls = new HashSet<acl>();
            this.dashboard_text = new HashSet<dashboard_text>();
        }

        public int id { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> rm_role { get; set; }
        public string no_pekerja { get; set; }
        public string lokasi { get; set; }
        public string direktorat { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tgl_lahir { get; set; }
        public Nullable<byte> jenis_kelamin { get; set; }
        public string agama { get; set; }
        public string susunan_keluarga { get; set; }
        public string NPWP { get; set; }
        public string alamat_pajak { get; set; }
        public string alamat_rumah { get; set; }
        public string alamat_ktp { get; set; }
        public Nullable<System.DateTime> tgl_mppk { get; set; }
        public Nullable<System.DateTime> tgl_pensiun { get; set; }
        public string sub_area { get; set; }
        public Nullable<System.DateTime> tgl_aktif { get; set; }
        public Nullable<System.DateTime> tmt_dapen_dplk { get; set; }
        public Nullable<System.DateTime> tmt_jabatan { get; set; }
        public Nullable<System.DateTime> tmt_gol_jabatan { get; set; }
        public string gol_upah_persero { get; set; }
        public Nullable<System.DateTime> tmt_gol_upah_persero { get; set; }
        public string gol_upah_ap { get; set; }
        public Nullable<System.DateTime> tmt_gol_upah_ap { get; set; }
        public string layering { get; set; }
        public string pendidikan_terakhir { get; set; }
        public string status_pekerja { get; set; }

        public virtual ICollection<users_keluarga> users_keluarga { get; set; }
        public virtual ICollection<users_kursus> users_kursus { get; set; }
        public virtual ICollection<users_nilai_kinerja> users_nilai_kinerja { get; set; }
        public virtual ICollection<users_pendidikan> users_pendidikan { get; set; }
        public virtual ICollection<users_pengalaman_kerja> users_pengalaman_kerja { get; set; }
        public virtual ICollection<users_penghargaan> users_penghargaan { get; set; }
        public virtual ICollection<users_penugasan> users_penugasan { get; set; }
        public virtual ICollection<users_riwayat_gol_upah_persero> users_riwayat_gol_upah_persero { get; set; }
        public virtual ICollection<users_sertifikasi> users_sertifikasi { get; set; }
        public virtual ICollection<users_tindakan_disiplin> users_tindakan_disiplin { get; set; }
        public virtual users_jabatan users_jabatan { internal get; set; }
        public virtual users_jabatan_parent users_jabatan_parent { get; set; }
        public virtual string status_pensiun { get; set; }
        public virtual ICollection<acl> acls { get; set; }
        public virtual ICollection<dashboard_text> dashboard_text { get; set; }
    }
}
