//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class users_keluarga
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string nama { get; set; }
        public string hubungan { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tgl_lahir { get; set; }

        public virtual user user { internal get; set; }
    }
    
}
