//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace relmon.Models
{
    public partial class users_jabatan
    {
        public users_jabatan()
        {
            this.users = new HashSet<user>();
        }

        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }
        public Nullable<int> company_id { get; set; }
        public string golongan { get; set; }
        public Nullable<int> cost_centre { get; set; }

        public virtual company company { internal get; set; }
        public virtual ICollection<user> users { internal get; set; }
        public virtual company2 company2 { get; set; }
        public virtual string nama_parent { get; set; }
        public virtual string nama_cost_centre { get; set; }
        public virtual int level { get; set; }
    }

    public partial class users_jabatan_parent
    {
        public users_jabatan_parent()
        {
            this.users = new HashSet<user>();
        }

        public int id { get; set; }
        public string nama { get; set; }
        public Nullable<int> parent { get; set; }
        public string deskripsi { get; set; }
        public Nullable<int> company_id { get; set; }
        public string golongan { get; set; }
        public Nullable<int> cost_centre { get; set; }

        public virtual company company { internal get; set; }
        public virtual ICollection<user> users { internal get; set; }
        public virtual company2 company2 { get; set; }
        public virtual string nama_parent { get; set; }
        public virtual string nama_cost_centre { get; set; }
        public virtual int level { get; set; }
    }

}
